# Generated by Django 4.2.28 on 2026-05-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
